version: '3.7'
services:
  client-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: cliente-service:0.2
    ports:
      - 8091:8091
    environment:
      - TZ=America/Lima