version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: reto-api
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8091:8091
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: reto-api
      MYSQL_USER: root
      MYSQL_PASSWORD: password
volumes:
  mysql_data:
